language: java
jdk:
  - openjdk17

branches:
    only:
      - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - u_genuine@naver.com
    on_success: always # 성공 시에도 항상 이메일 전송
    on_failure: always # 실패 시에도 항상 이메일 전송